baseURL: "https://xyslong.github.io" 
title: Xingyu Long
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: CReA Lab
          url: crealab/
          weight: 2
        - name: Miscellaneous
          url: misc/
          weight: 3
        - name: Communities
          url: communities/
          weight: 4
        - name: Location
          url: location/
          weight: 5

params:
    description: "I'm a PhD student in Cognitive Science at the University of Vienna."
    author: Xingyu Long
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Misc","Location","Research"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Xingyu Long
          subtitle: "My name is Xingyu Long / 龙星羽. I'm a PhD student in Cognitive Science at the University of Vienna, where I investigate visual perception together with art historians and psychologists."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: CReA Lab
              url: crealab/
            - name: Miscellaneous
              url: misc/
            - name: Communities
              url: communities/

    socialIcons:
        - name: LinkedIn
          url: https://www.linkedin.com/in/xingyu-long-15b198105/
        - name: Email
          url: mailto:xingyu.long@univie.ac.at
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=I3P7fhgAAAAJ/
        - name: GitHub
          url: https://github.com/xyslong/
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Xingyu Long"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2