baseURL: "https://xyslong.github.io" 
title: Xingyu Long
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Miscellaneous
          url: misc/
          weight: 5
        - name: Location
          url: location/
          weight: 3
        - name: Research
          url: research/
          weight: 3

params:
    description: "I am a PhD student in Cognitive Science at the University of Vienna."
    author: Xingyu Long
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Misc","Location","Research"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Xingyu Long
          subtitle: "My name is Xingyu Long (龙星羽) and I am a PhD student in Cognitive Science at the University of Vienna, where I investigate visual perception in collaboration with art historians and psychologists."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: https://ufind.univie.ac.at/en/person.html?id=1012161/
            - name: CReA Lab
              url: https://crea.univie.ac.at/
            - name: VDS CoBeNe
              url: https://vds-cobene.univie.ac.at/
            - name: Misc
              url: misc/

    socialIcons:
        - name: LinkedIn
          url: https://www.linkedin.com/in/xingyu-long-15b198105/
        - name: Email
          url: mailto:xingyu.long@univie.ac.at
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=I3P7fhgAAAAJ/
        - name: GitHub
          url: https://github.com/xyslong/
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Xingyu Long"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2